### ISSUE TITLE
Use browser-grade css or html parser from cobalt.foo

### ISSUE THREAD

**Issue by blockspacer** [marcj/Pesto#2]
See https://github.com/blockspacer/skia-opengl-emscripten/blob/master/src/cobalt/cobalt_css_parser.cmake as CMake integration example

Pros: tiny parser based on chromium

Cons: Requires chromium`s base and icu

May be interesting:
https://www.reddit.com/r/cpp/comments/dcwq61/how_you_can_create_c_gui_framework_and_maybe_earn/

**Comment by marcj** [comment]
Good idea. I plan to rework the api to use intermediate mode in combination with a virtual dom that uses css to style the stuff. It has then mostly the workflow of React, so another more powerful css parser would be handy. Maybe use directly something like SCSS.

What do you mean with that reddit link? There are only 2 comments

**Comment by blockspacer** [comment]
> Good idea. I plan to rework the api to use intermediate mode in combination with a virtual dom that uses css to style the stuff. It has then mostly the workflow of React, so another more powerful css parser would be handy. Maybe use directly something like SCSS.
> 
> What do you mean with that reddit link? There are only 2 comments

Reddit link broken, here fixed link https://github.com/blockspacer/skia-opengl-emscripten/issues/9
